// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React from 'react';

export async function getRoutes() {
  const routes = {"1":{"path":"/","redirect":"/template","parentId":"ant-design-pro-layout","id":"1"},"2":{"name":"模板管理","path":"/template","parentId":"ant-design-pro-layout","id":"2"},"3":{"name":"代码生成","path":"/codegen","parentId":"ant-design-pro-layout","id":"3"},"4":{"name":"AI定制","path":"/ai-custom","parentId":"ant-design-pro-layout","id":"4"},"5":{"name":"预览测试","path":"/preview","parentId":"ant-design-pro-layout","id":"5"},"6":{"name":"发布部署","path":"/publish","parentId":"ant-design-pro-layout","id":"6"},"ant-design-pro-layout":{"id":"ant-design-pro-layout","path":"/","isLayout":true}} as const;
  return {
    routes,
    routeComponents: {
'1': React.lazy(() => import('./EmptyRoute')),
'2': React.lazy(() => import(/* webpackChunkName: "p__Template__index" */'@/pages/Template/index.tsx')),
'3': React.lazy(() => import(/* webpackChunkName: "p__CodeGen__index" */'@/pages/CodeGen/index.tsx')),
'4': React.lazy(() => import(/* webpackChunkName: "p__AICustom__index" */'@/pages/AICustom/index.tsx')),
'5': React.lazy(() => import(/* webpackChunkName: "p__Preview__index" */'@/pages/Preview/index.tsx')),
'6': React.lazy(() => import(/* webpackChunkName: "p__Publish__index" */'@/pages/Publish/index.tsx')),
'ant-design-pro-layout': React.lazy(() => import(/* webpackChunkName: "umi__plugin-layout__Layout" */'/Users/chihuan/Documents/CodeEvolve/frontend/src/.umi/plugin-layout/Layout.tsx')),
},
  };
}
